spring:
  datasource:
    url: "jdbc:mysql://${db_url}:${db_port}/${db_schema}?allowPublicKeyRetrieval=true&useSSL=false" #"jdbc:mysql://${localhost}:3306/test_db"
    username: ${db_username} #root
    password: ${db_pwd}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: ${service_port}

kafka:
  bootstrap-servers: http://${kafka_url}:${kafka_port}
  topic: ${kafka_topic} #delivery.complaint.tickets
  consumer:
    group-id: ${kafka_consumer_group} #automated_ticketing_consumer_group
    auto-offset-reset: earliest

logging:
  level:
    com.callsign.service.ticketing: ${logging_level} #${logging_level} com.callsign.service.ticketing